<?php


// Here's what the result would look like with your data:
$postCodeArray = array(
    'BR11AA' => array(
        'Flat 38, Henry House, Ringers Road',
        'Flat 27, Henry House, Ringers Road',
        'Flat 28, Henry House, Ringers Road',
        'Flat 29, Henry House, Ringers Road',
        'Flat 30, Henry House, Ringers Road',
        'Flat 31, Henry House, Ringers Road',
        'Flat 32, Henry House, Ringers Road',
        'Flat 33, Henry House, Ringers Road',
        'Flat 34, Henry House, Ringers Road',
        'Flat 35, Henry House, Ringers Road',
        'Flat 36, Henry House, Ringers Road',
        'Flat 37, Henry House, Ringers Road',
        'Flat 26, Henry House, Ringers Road',
        'Flat 39, Henry House, Ringers Road',
        'Flat 40, Henry House, Ringers Road',
        'Flat 41, Henry House, Ringers Road',
        'Flat 42, Henry House, Ringers Road',
        'Flat 43, Henry House, Ringers Road',
        'Flat 44, Henry House, Ringers Road',
        'Flat 45, Henry House, Ringers Road',
        'Flat 46, Henry House, Ringers Road',
        'Flat 47, Henry House, Ringers Road',
        'Flat 48, Henry House, Ringers Road',
        'Flat 49, Henry House, Ringers Road',
        'Flat 14, Henry House, Ringers Road',
        'Flat 2, Henry House, Ringers Road',
        'Flat 3, Henry House, Ringers Road',
        'Flat 4, Henry House, Ringers Road',
        'Flat 5, Henry House, Ringers Road',
        'Flat 6, Henry House, Ringers Road',
        'Flat 7, Henry House, Ringers Road',
        'Flat 8, Henry House, Ringers Road',
        'Flat 9, Henry House, Ringers Road',
        'Flat 10, Henry House, Ringers Road',
        'Flat 11, Henry House, Ringers Road',
        'Flat 12, Henry House, Ringers Road',
        'Flat 1, Henry House, Ringers Road',
        'Flat 15, Henry House, Ringers Road',
        'Flat 16, Henry House, Ringers Road',
        'Flat 17, Henry House, Ringers Road',
        'Flat 18, Henry House, Ringers Road',
        'Flat 19, Henry House, Ringers Road',
        'Flat 20, Henry House, Ringers Road',
        'Flat 21, Henry House, Ringers Road',
        'Flat 22, Henry House, Ringers Road',
        'Flat 23, Henry House, Ringers Road',
        'Flat 24, Henry House, Ringers Road',
        'Flat 25, Henry House, Ringers Road'
    ),
    'BR11AB' => array(
        'Apartment 1, The Old Post Office 3B, East Street',
        'Apartment 2, The Old Post Office 3B, East Street',
        'Apartment 3, The Old Post Office 3B, East Street',
        'Apartment 4, The Old Post Office 3B, East Street',
        'Apartment 5, The Old Post Office 3B, East Street',
        'Apartment 6, The Old Post Office 3B, East Street',
        'Apartment 7, The Old Post Office 3B, East Street',
        'Apartment 8, The Old Post Office 3B, East Street',
        '3 East Street',
        'Bird & Bun Rotisserie, 3A, East Street'
    )
);
?>